---
- name: Upgrade all packages to latest version
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  become: yes

- name: Install MongoDB
  apt: name=mongodb state=latest
  become: yes
